classdef tChartDocumentation < matlab.unittest.TestCase
    %TCHARTDOCUMENTATION Tests for generated chart documentation.

    % Copyright 2026 The MathWorks, Inc.

    properties ( Access = private )
        % Project root folder.
        ProjectRoot(1, 1) string
    end % properties ( Access = private )

    methods ( TestClassSetup )

        function generateDocumentation( testCase )

            % Regenerate the reference Markdown used by these tests.
            prj = currentProject();
            testCase.ProjectRoot = string( prj.RootFolder );
            generateChartReferencePages();

        end % generateDocumentation

    end % methods ( TestClassSetup )

    methods ( Test )

        function tChartLandingPageLinksSeparateListingPages( testCase )

            chartName = "WaterfallChart";
            chartPage = testCase.chartReferenceFile( chartName + ".md" );
            classPage = testCase.chartReferenceFile( ...
                chartName + "ClassReference.md" );
            sourcePage = testCase.chartReferenceFile( ...
                chartName + "SourceCode.md" );
            testPage = testCase.chartReferenceFile( ...
                chartName + "UnitTest.md" );

            chartText = readTextFile( chartPage );
            classText = readTextFile( classPage );
            sourceText = readTextFile( sourcePage );
            testText = readTextFile( testPage );

            testCase.verifyTrue( contains( chartText, ...
                "# Waterfall Chart" ), ...
                "The chart landing page did not use the display name." )
            testCase.verifyFalse( contains( chartText, ...
                "# `WaterfallChart`" ), ...
                "The chart landing page used the class name as code." )
            testCase.verifyTrue( contains( chartText, ...
                chartName + "ClassReference.md" ), ...
                "The chart landing page did not link to the " + ...
                "class documentation page." )
            testCase.verifyTrue( contains( chartText, ...
                chartName + "SourceCode.md" ), ...
                "The chart landing page did not link to the " + ...
                "separate source code listing page." )
            testCase.verifyTrue( contains( chartText, ...
                chartName + "UnitTest.md" ), ...
                "The chart landing page did not link to the " + ...
                "separate unit test listing page." )
            testCase.verifyFalse( contains( chartText, ...
                "../examples/" + chartName + ".md" ), ...
                "The chart landing page still links to the separate " + ...
                "example page." )
            testCase.verifyTrue( contains( chartText, ...
                "../examples/images/WaterfallChart.png" ), ...
                "The chart landing page did not include the chart image." )
            testCase.verifyTrue( contains( chartText, ...
                "Show the cumulative evolution of an initial value." ), ...
                "The chart landing page description did not start " + ...
                "with a capital letter." )
            testCase.verifyFalse( contains( chartText, ...
                "## Description" ), ...
                "The chart landing page still contains the " + ...
                "duplicated description section." )
            testCase.verifyFalse( contains( chartText, ...
                "## Documentation Page" ), ...
                "The chart landing page still contains the " + ...
                "duplicated documentation link section." )
            testCase.verifyFalse( contains( chartText, ...
                "matlab.graphics.chartcontainer.ChartContainer" ), ...
                "The chart landing page still embeds source code." )
            testCase.verifyTrue( contains( classText, "## Syntax" ), ...
                "The class documentation page did not include syntax." )
            testCase.verifyTrue( contains( classText, ...
                "WC = WaterfallChart(name, value, ...)" ), ...
                "The class documentation page did not include the " + ...
                "assigned constructor syntax." )
            testCase.verifyTrue( contains( classText, ...
                "## Properties" ), ...
                "The class documentation page did not include " + ...
                "properties." )
            testCase.verifyTrue( contains( classText, "## Methods" ), ...
                "The class documentation page did not include methods." )
            testCase.verifyTrue( contains( classText, "## Examples" ), ...
                "The class documentation page did not include examples." )
            testCase.verifyTrue( contains( classText, ...
                "WC = WaterfallChart( " + ...
                """Parent"", f, ""Data"", data );" ), ...
                "The class documentation page did not embed the " + ...
                "example content." )
            testCase.verifyFalse( contains( classText, ...
                "Open the runnable example page" ), ...
                "The class documentation page still links to the " + ...
                "separate example page." )
            testCase.verifyTrue( contains( classText, "`Data`" ), ...
                "The class documentation page did not include a " + ...
                "public chart property." )
            testCase.verifyFalse( contains( classText, "`Axes`" ), ...
                "The class documentation page included a test-only " + ...
                "implementation property." )
            testCase.verifyTrue( contains( sourceText, ...
                "classdef WaterfallChart <" ) && ...
                contains( sourceText, ...
                "matlab.graphics.chartcontainer.ChartContainer" ), ...
                "The source code listing page did not include the " + ...
                "chart class definition." )
            testCase.verifyTrue( contains( testText, ...
                "classdef tWaterfallChart < tChart" ), ...
                "The unit test listing page did not include the " + ...
                "chart test class definition." )

        end % tChartLandingPageLinksSeparateListingPages

        function tChartWithSpecificTestIncludesUnitTestPage( testCase )

            chartName = "AircraftChart";
            chartPage = testCase.chartReferenceFile( chartName + ".md" );
            testPage = testCase.chartReferenceFile( ...
                chartName + "UnitTest.md" );
            chartText = readTextFile( chartPage );

            testCase.verifyTrue( isfile( testPage ), ...
                "A unit test listing page was not generated for a " + ...
                "chart with a chart-specific test file." )
            testCase.verifyTrue( contains( chartText, ...
                chartName + "UnitTest.md" ), ...
                "The chart landing page did not link to the " + ...
                "chart-specific unit test listing." )

        end % tChartWithSpecificTestIncludesUnitTestPage

        function tHelpTocNestsReferencePagesByChart( testCase )

            tocFile = fullfile( testCase.ProjectRoot, ...
                "tbx", "chartsdoc", "helptoc.md" );
            tocText = readTextFile( tocFile );

            testCase.verifyTrue( contains( tocText, ...
                "    * [Waterfall Chart](charts/WaterfallChart.md)" ), ...
                "The help table of contents did not contain the " + ...
                "chart subsection." )
            testCase.verifyFalse( contains( tocText, ...
                "examples/WaterfallChart.md" ), ...
                "The help table of contents still links to the " + ...
                "separate example page." )
            testCase.verifyTrue( contains( tocText, ...
                "      * [Class Documentation and Examples]" + ...
                "(charts/WaterfallChartClassReference.md)" ), ...
                "The help table of contents did not nest the class " + ...
                "documentation and examples page under the chart." )
            testCase.verifyTrue( contains( tocText, ...
                "      * [Source Code Listing]" + ...
                "(charts/WaterfallChartSourceCode.md)" ), ...
                "The help table of contents did not nest the source " + ...
                "listing page under the chart." )
            testCase.verifyTrue( contains( tocText, ...
                "      * [Unit Test Listing]" + ...
                "(charts/WaterfallChartUnitTest.md)" ), ...
                "The help table of contents did not nest the unit " + ...
                "test listing page under the chart." )

        end % tHelpTocNestsReferencePagesByChart

        function tClassDocumentationIncludesReadOnlyProperties( testCase )

            classPage = testCase.chartReferenceFile( ...
                "CircularNetFlowChartClassReference.md" );
            classText = readTextFile( classPage );

            testCase.verifyTrue( contains( classText, "`NetFlow`" ), ...
                "The class documentation page did not include a " + ...
                "public read-only property." )
            testCase.verifyTrue( contains( classText, "read-only" ), ...
                "The class documentation page did not label " + ...
                "read-only properties." )

        end % tClassDocumentationIncludesReadOnlyProperties

    end % methods ( Test )

    methods ( Access = private )

        function file = chartReferenceFile( testCase, fileName )

            file = fullfile( testCase.ProjectRoot, ...
                "tbx", "chartsdoc", "charts", fileName );

        end % chartReferenceFile

    end % methods ( Access = private )

end % classdef

function text = readTextFile( file )
%READTEXTFILE Read a text file as a string scalar.

arguments ( Input )
    file(1, 1) string
end % arguments ( Input )

arguments ( Output )
    text(1, 1) string
end % arguments ( Output )

text = strjoin( readlines( file ), newline() );

end % readTextFile
